main/urls.py
from django.conf.urls import patterns, url

from main.views import CarListView, CarDetailView, RentCreateView, MyRentedCarListView, RentDeleteView, AddCommentView, carRate

urlpatterns = patterns('',
    url(r'^$', CarListView.as_view(), {'page': 1}, name='index'),
    # example: car/list
    url(r'^car/list/$', CarListView.as_view(), {'page': 1}, name='car_list_default'),
    # example: car/list/2
    url(r'^car/list/(?P<page>[0-9]+)/$', CarListView.as_view(), name='car_list'),
    # example: car/12
    url(r'^car/(?P<car_id>[0-9]+)/$', CarDetailView.as_view(), name='car_detail'),
	# example: car/12/add_comment
    url(r'^car/(?P<car_id>[0-9]+)/add_comment$', AddCommentView.as_view(), name='add_comment'),
    # example: rent/1
    url(r'^rent/(?P<car_id>[0-9]+)/$', RentCreateView.as_view(), name='rent_create'),
    #
    url(r'^rent/cancel/(?P<rent_id>[0-9]+)/$', RentDeleteView.as_view(), name='rent_delete'),
    #
    url(r'^history/list/$', MyRentedCarListView.as_view(), {'page': 1}, name='my_history_list_default'),
    #
    url(r'^history/list/(?P<page>[0-9]+)/$', MyRentedCarListView.as_view(), name='my_history_list'),
    #
    url(r'^carRate/$', carRate, name='game_rate'),

)

rentalhouse/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^about/$', views.flatpage, {'url': '/about/'}, name='about'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, timedelta


class Client(models.Model):
	user = models.OneToOneField(User)
	phone_number = models.CharField(max_length=12, unique=True)
	pesel = models.CharField(max_length=12, unique=True)

	def __str__(self):
		return self.first_name + " " + self.last_name


class CarType(models.Model):
	name = models.CharField(max_length=30, unique=True)

	def __str__(self):
		return self.name


class EngineType(models.Model):
	name = models.CharField(max_length=30, unique=True)

	def __str__(self):
		return self.name


class CarAccessory(models.Model):
	name = models.CharField(max_length=30, unique=True)

	def __str__(self):
		return self.name


class Car(models.Model):
	car_image = models.ImageField()
	car_type = models.ForeignKey(CarType)
	engine_type = models.ForeignKey(EngineType)
	car_accessories = models.ManyToManyField(CarAccessory)
	producer = models.CharField(max_length=30)
	model = models.CharField(max_length=30)
	engine_capacity = models.DecimalField(max_digits=6, decimal_places=2)
	engine_horsepower = models.DecimalField(max_digits=6, decimal_places=2)
	seats_quantity = models.IntegerField()
	doors_quantity = models.IntegerField()
	load_capacity = models.IntegerField()
	production_year = models.IntegerField()
	vin_number = models.CharField(max_length=17, unique=True)
	rent_cost = models.DecimalField(max_digits=8, decimal_places=2)

	comments = models.ManyToManyField(User, through='Comment', through_fields=('car', 'user'), related_name='users_that_commented')
	ratings = models.ManyToManyField(User, through='Rating', through_fields=('car', 'user'), related_name='users_that_rated')

	def __str__(self):
		return self.car_type.name + " (" + self.vin_number + ")"


class Rent(models.Model):
	client = models.ForeignKey(User)
	car = models.ForeignKey(Car)
	rent_cost = models.DecimalField(max_digits=8, decimal_places=2)
	start_date = models.DateField()
	end_date = models.DateField()

	@property
	def is_start_past_or_today(self):
		if date.today() >= self.start_date:
			return True
		return False

	@property
	def is_end_future_or_today(self):
		if date.today() <= self.end_date:
			return True
		return False

	@property
	def can_be_cancelled(self):
		if date.today() + timedelta(days=3) <= self.start_date:
			return True
		return False

	def __str__(self):
		client_and_car_info = self.client.__str__() + ", " + self.car.__str__()
		date_range_info = "from " + self.start_date.__str__() + " to " + self.end_date.__str__()
		cost_info = "(" + self.rent_cost.__str__() + ")"
		return client_and_car_info + " " + date_range_info + " " + cost_info

class Comment(models.Model):
	user = models.ForeignKey(User)
	car = models.ForeignKey(Car)
	content = models.CharField(max_length = 1000)
	date = models.DateTimeField()
	comment_status = models.BooleanField(default = False)

	class Meta:
		ordering = ['-date',]

	def __str__(self):
		return self.content

class Rating(models.Model):
	user = models.ForeignKey(User)
	car = models.ForeignKey(Car)
	rating = models.IntegerField()
	date = models.DateTimeField()

	class Meta:
		unique_together = ('user', 'car')

	def clean(self):
		if(self.rating < 1 or self.rating > 10):
			raise ValidationError('Rating needs to be in a range of 1 to 10!')

main/forms.py
from django.forms import ModelForm, ValidationError, DateInput, DateField, Form, ChoiceField, Select
from django.forms.extras.widgets import SelectDateWidget
from main.models import *
from django import forms

from datetime import datetime

from main.models import Rent


class RentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(RentForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget = DateInput(attrs={'class':'form-control'},format=('%Y-%m-%d'))
        self.fields['end_date'].widget = DateInput(attrs={'class':'form-control'},format=('%Y-%m-%d'))
        #start_date = DateField(label='Start date', input_formats=['%Y-%m-%d'], attrs={'class':'form-control'})
        #end_date = DateField(label='End date', input_formats=['%Y-%m-%d'], attrs={'class':'form-control'})

    def clean(self):
        data = super(RentForm, self).clean()
        start = data.get('start_date')
        end = data.get('end_date')
        if start and end:
            now = datetime.now().date()
            diff = (now - start).total_seconds()
            if diff > 0:
                raise ValidationError("Both dates have to be in the future.")

            days = (end - start).days
            if days < 1:
                raise ValidationError("The rent period has to be at least one full day.")

    class Meta:
        model = Rent
        fields = ['start_date', 'end_date']


class CarFilterForm(Form):
    CAR_TYPES = [(i.id, i.name) for i in CarType.objects.all()]
    CAR_TYPES.insert(0, ("", "All"))

    ACCESSORIES = [(i.id, i.name) for i in CarAccessory.objects.all()]

    ENGINE_TYPES = [(i.id, i.name) for i in EngineType.objects.all()]
    ENGINE_TYPES.insert(0, ("", "All"))

    car_name = forms.CharField(required=False)
    car_type = ChoiceField(required=False, widget=Select, choices=CAR_TYPES)
    engine_type = ChoiceField(required=False, widget=Select, choices=ENGINE_TYPES)
    accessories = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=ACCESSORIES)
    price_from = forms.CharField(required=False, widget=forms.NumberInput)
    price_to = forms.CharField(required=False, widget=forms.NumberInput)
    start_date = forms.DateField(required=False, widget=DateInput(attrs={'class': 'datepicker'}))
    end_date = forms.DateField(required=False, widget=DateInput(attrs={'class': 'datepicker'}))
    min_rating = forms.CharField(required=False, widget=forms.NumberInput(attrs={'type': 'number', 'min': '0', 'max': '10', 'step': '1'}))


class CommentForm(ModelForm):
		car_id = forms.CharField(widget=forms.HiddenInput)
		content = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

		def __init__(self, *args, **kwargs):
				super(CommentForm, self).__init__(*args, **kwargs)

		def clean(self):
				data = super(CommentForm, self).clean()

		class Meta:
				model = Comment
				fields = ['content']

main/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, View
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.forms.utils import ErrorList
from django.shortcuts import Http404, render
from django.http import HttpResponseRedirect
from django.db.models import Avg, Count
from main.models import Car, Rent, User
from main.forms import *
from datetime import datetime


class CarListView(ListView):
    model = Car
    template_name = 'main/car_list.html'
    context_object_name = 'car_list'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        context['filter'] = CarFilterForm(self.request.GET)

        return context

    def get_queryset(self):
        qs = Car.objects.all()
        rents = Rent.objects.all()

        form = CarFilterForm(self.request.GET)
        if form.is_valid():
            car_name = form.cleaned_data['car_name']
            car_type = form.cleaned_data['car_type']
            engine_type = form.cleaned_data['engine_type']
            accessories = form.cleaned_data['accessories']
            price_from = form.cleaned_data['price_from']
            price_to = form.cleaned_data['price_to']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            min_rating = form.cleaned_data['min_rating']

            if start_date:
                qs = qs.exclude(Q(rent__start_date__lte=start_date) & Q(rent__end_date__gte=start_date))
            if end_date:
                qs = qs.exclude(Q(rent__start_date__lte=end_date) & Q(rent__end_date__gte=end_date))
            if start_date and end_date:
                qs = qs.exclude(Q(rent__start_date__gte=start_date) & Q(rent__end_date__lte=end_date))
            if car_name:
                qs = qs.filter(Q(producer__contains=car_name) |Q(model__contains=car_name))
            if car_type:
                qs = qs.filter(car_type=car_type)
            if engine_type:
                qs = qs.filter(engine_type=engine_type)
            if price_from:
                qs = qs.filter(rent_cost__gte=price_from)
            if price_to:
                qs = qs.filter(rent_cost__lte=price_to)
            if min_rating:
                qs = qs.annotate(avg_rating=Avg('rating__rating')).filter(avg_rating__gt=min_rating)

            for accessory in accessories:
                qs = qs.filter(car_accessories__id=accessory)

        return qs

class MyRentedCarListView(ListView):
    model = Rent
    template_name = 'main/my_rented_car_list.html'
    context_object_name = 'my_rented_car_list'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(MyRentedCarListView, self).get_context_data(**kwargs)

        category = self.kwargs.get('category')
        if category:
            context['current_category'] = category
        return context

    def get_queryset(self):
        rents = Rent.objects.all().filter(client=self.request.user.id).order_by("-start_date", "-end_date")

        return rents

class CarDetailView(DetailView):
    model = Car
    template_name = 'main/car_detail.html'
    context_object_name = 'car'
    pk_url_kwarg = 'car_id'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(CarDetailView, self).get_context_data(**kwargs)
        context['accessories'] = context['car'].car_accessories.all()
        context['form'] = CommentForm(initial={'car_id': context['car'].id})
        context['rating'] = Rating.objects.all().filter(car= context['car'].id).aggregate(Avg('rating'))
        return context

class AddCommentView(View):
    model = Comment
    form_class = CommentForm
    template_name = 'main/car_detail.html'
    context_object_name = 'form'
    pk_url_kwarg = 'car_id'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AddCommentView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        self.request = request
        if form.is_valid():
            self.form_valid(form)
            return HttpResponseRedirect('/car/' + form.cleaned_data['car_id'] + '/')
        return HttpResponseRedirect('/car/' + form.cleaned_data['car_id'] + '/')

    def get_context_data(self, **kwargs):
        context = super(AddCommentView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(self.request.POST)
        context['car'] = self.car
        return context

    def form_valid(self, form):
        form.instance.content = form.cleaned_data['content']
        if self.request.user.is_authenticated():
            form.instance.user = get_object_or_404(User, username=self.request.user.username)
        else:
            form.instance.user = None
        form.instance.date = datetime.now()
        form.instance.car = get_object_or_404(Car, id=form.cleaned_data['car_id'])
        rents = Rent.objects.filter(car=form.instance.car).filter(Q(end_date__lte=form.instance.date)).filter(Q(client=form.instance.user)).count()
        if rents > 0:
            form.instance.comment_status = True
        else:
            form.instance.comment_status = False
        form.save()
        return True


class RentCreateView(SuccessMessageMixin, CreateView):
    model = Rent
    form_class = RentForm
    success_url = '/'
    success_message = "Car was created successfully purchased."

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(RentCreateView, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        self.car = get_object_or_404(Car, pk=self.kwargs['car_id'])
        return super(RentCreateView, self).get_form_kwargs()

    def get_context_data(self, **kwargs):
        context = super(RentCreateView, self).get_context_data(**kwargs)
        context['car'] = self.car
        return context

    def form_valid(self, form):
        start = form.cleaned_data['start_date']
        end = form.cleaned_data['end_date']

        # check if this car is available in requested period
        rents = Rent.objects.filter(car=self.car).filter(Q(start_date__lte=end) & Q(end_date__gte=start)).count()
        if rents > 0:
            errors = form._errors.setdefault("start_date", ErrorList())
            errors.append("This car is unavailable during this time. Please, select another dates.")
            return self.form_invalid(form)

        # populate Rent fields
        form.instance.client = self.request.user
        form.instance.rent_cost = self.car.rent_cost * (end - start).days
        form.instance.car_id = self.car.pk
        form.save()
        return super(RentCreateView, self).form_valid(form)


class RentDeleteView(DeleteView):
    model = Rent
    template_name = 'main/rent_cancel.html'
    pk_url_kwarg = 'rent_id'
    context_object_name = 'rent'
    success_url = '/history/list/'

def carRate(request):
   if request.method == 'POST':
        rate = request.POST['rate']
        car = request.POST['car']
        car = Car.objects.get(id=car)
        user = request.user
        try:
            rating = Rating.objects.get(car = car, user = user)
            rating.rating = rate
        except Rating.DoesNotExist:
            rating = Rating(car = car, user = user, rating = rate, date=datetime.now())
        rating.save();

        return HttpResponseRedirect('/history/list/')
   else:
        return HttpResponseRedirect('/')

main/templates/main/car_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
		<div class="well well-sm">
			<strong>Select View:</strong>
			<div class="btn-group">
				<a href="#" id="list" class="btn btn-default btn-sm">List</a>
				<a href="#" id="grid" class="btn btn-default btn-sm">Grid</a>
			</div>
			<div class="pull-right">
				<a href="#filters" class="btn btn-default btn-sm" data-toggle="collapse" >Show filters</a>
			</div>
			<div id="filters" class="collapse">
				<strong>Filtering</strong>
				<form id="filter" action="{{ request.path }}" method="get">
					<div class="row">
						<div class="col-md-4 form-horizontal">
							<div class="form-group">
								<label for="{{ filter.car_name.id_for_label }}" class="col-md-4 control-label">Name</label>
								<div class="col-md-8">
									{{ filter.car_name }}
								</div>
							</div>
							<div class="form-group">
								<label for="{{ filter.car_type.id_for_label }}" class="col-md-4 control-label">Type</label>
								<div class="col-md-8">
									{{ filter.car_type }}
								</div>
							</div>
							<div class="form-group">
								<label for="{{ filter.engine_type.id_for_label }}" class="col-md-4 control-label">Engine type</label>
								<div class="col-md-8">
									{{ filter.engine_type }}
								</div>
							</div>
							<div class="form-group">
								<label for="{{ filter.min_rating.id_for_label }}" class="col-md-4 control-label">Minimal rating</label>
								<div class="col-md-8">
									{{ filter.min_rating }}
								</div>
							</div>
						</div>
						<div class="col-md-4 form-horizontal">
							<div class="form-group">
								<label for="{{ filter.price_from.id_for_label }}" class="col-md-4 control-label">Price from</label>
								<div class="col-md-8">
									{{ filter.price_from }}
								</div>
							</div>
							<div class="form-group">
								<label for="{{ filter.price_to.id_for_label }}" class="col-md-4 control-label">Price to</label>
								<div class="col-md-8">
									{{ filter.price_to }}
								</div>
							</div>
							<div class="form-group">
								<label for="{{ filter.start_date.id_for_label }}" class="col-md-4 control-label">Start date</label>
								<div class="col-md-8">
									{{ filter.start_date }}
								</div>
							</div>
							<div class="form-group">
								<label for="{{ filter.end_date.id_for_label }}" class="col-md-4 control-label">End date</label>
								<div class="col-md-8">
									{{ filter.end_date }}
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group">
								{{ filter.accessories.label_tag }}
								{{ filter.accessories }}
							</div>
						</div>
					</div>
					<input type="submit" value="Filter" class="btn btn-default btn-sm" />
					<button type="button" class="btn btn-default btn-sm" onclick="clearFilters()">Clear</button>
				</form>
			</div>
		</div>
		<div id="cars" class="row list-group">
			{% if car_list %}
				{% for car in car_list %}
					<div class="item  col-xs-4 col-lg-4">
						<div class="thumbnail">
							<div class="images">
								<div class="imageContainer">
									<a><img class="group list-group-image" {% if car.car_image %} src="/{{ car.car_image }}"  {% else %} src="/static/static/js/npm.js" {% endif %}/></a>
								</div>
							</div>
							<div class="caption">
								<h3 class="group inner list-group-item-heading">
									{{ car.producer }} {{ car.model }} ({{ car.car_type }})
								</h3>
								<p class="group inner list-group-item-text">
									{{ car.engine_capacity }}cm<sup>3</sup><br> {{ car.engine_horsepower }}KM
								</p>
								<div class="row">
									<div class="col-xs-12 col-md-4">
										<p class="lead">
											{{car.rent_cost}}zł
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-xs-12 col-md-6">
										<a class="btn btn-info btn-block" href="{% url 'main:car_detail' car.pk %}" role="button">Show details &raquo;</a>
									</div>
									<div class="col-xs-12 col-md-6">
										<a class="btn btn-success btn-block" href="{% url 'main:rent_create' car.pk %}?ref={{ request.path }}" role="button">Create order &raquo;</a>
									</div>
								</div>
								<p></p>
							</div>
						</div>
					</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    function clearFilters() {
        $("#id_car_name").val("");
        $("#id_car_type").val("");
        $("#id_engine_type").val("");
        $("#id_accessories").val("");
        $("#id_price_from").val("");
        $("#id_price_to").val("");
        $("#id_start_date").val("");
        $("#id_end_date").val("");
        $("#id_min_rating").val("");
        $("#filter").submit();
    }
</script>
{% endblock %}

main/templates/main/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
'
    <div class="container">
        <h1>Contact</h1>  
    </div>


{% endblock %}

main/templates/main/my_rented_car_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h1>
        My rents history
    </h1>
		<div id="cars" class="row list-group">
		    {% if my_rented_car_list %}
            {% if is_paginated %}
                <div class="pagination">
                     <ul class="pagination">
                         {% for i in page_obj.paginator.page_range %}
                            <li {%if page_obj.number == i%}class="active"{%endif%}><a href="/history/list/{{i}}">{{i}}</a></li>
                         {%endfor%}
                     </ul>
                </div>
            {% endif %}
				{% for rent in my_rented_car_list %}
					<div class="row">
							<div class="col-md-4">
								<div class="imageContainer">
									<a><img class="group list-group-image" style="width:100%" {% if rent.car.car_image %} src="/{{ rent.car.car_image }}"  {% else %} src="/static/static/js/npm.js" {% endif %}/></a>
								</div>
							</div>
							<div class="col-md-4">
								<h3 class="group inner list-group-item-heading">
									{{ rent.car.producer }} {{ rent.car.model }} ({{ rent.car.car_type }})
								</h3>
                            	<p class="group inner list-group-item-text">
									{{ rent.car.engine_capacity }}cm<sup>3</sup><br> {{ rent.car.engine_horsepower }}KM
								</p>
								<div class="row">
									<div class="col-xs-12 col-md-4">
										<p class="lead">
											{{rent.car.rent_cost}}zł
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-xs-12 col-md-6">
										<a class="btn btn-info btn-block" href="{% url 'main:car_detail' rent.car.pk %}" role="button">Show details &raquo;</a>
									</div>

                                    {%if rent.is_start_past_or_today %}
									{% if user.is_authenticated %}


                     <form action="/carRate/" method="post">
                     {% csrf_token %}
                    <input type="hidden" name="car" value="{{rent.car.id}}">
                    <input type="hidden" class="form-control rate-input" name="rate" onchange="this.form.submit()">
                     <div class="col-xs-12 col-md-6 btn-group">
                         <button style ="width:100% " type="button" class="btn
                          {% for rate in rent.car.rating_set.all %}
                            {% if rate.user.id == user.id %}
                            {% if rate.rating > 8 %}
                             btn-success
                            {% elif rate.rating > 6 %}
                            btn-primary
                            {% elif rate.rating > 4 %}
                            btn-info
                            {% elif rate.rating > 2 %}
                            btn-warning
                            {% elif rate.rating >= 0 %}
                            btn-danger
                            {% endif %}
                            {% endif %}
                        {% endfor %}
                          dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                             Rating:
                         {% for rate in rent.car.rating_set.all %}
                            {% if rate.user.id == user.id %}
                             {{ rate.rating }}
                            {% endif %}
                        {% endfor %}
                             <span class="caret"></span>
                        </button>
                         <ul class="dropdown-menu" role="menu">
                             {% with '0 1 2 3 4 5 6 7 8 9 10' as list %}
                             {% for i in list.split %}
                                <li><a class = "change-rate" href="#">{{ i }}</a></li>
                             {% endfor %}
                             {% endwith %}
                         </ul>
                     </div>
                     </form>
            {% endif%}
                                    {%endif%}
									{%if rent.can_be_cancelled %}
									<div class="col-xs-12 col-md-6">
										<a class="btn btn-success btn-block" href="{% url 'main:rent_delete' rent.pk %}" role="button">Cancel reservation</a>
									</div>
                                    {%endif%}
								</div>
								<p></p>
							</div>
                            <div class="col-md-4">
								<h3 class="group inner list-group-item-heading">
									From: {{ rent.start_date }}<br/>
                                    To: {{ rent.end_date }}<br/>
                                    <b>Total: {{rent.rent_cost}}zł</b>
								</h3>
                                {% if rent.is_end_future_or_today and rent.is_start_past_or_today %}
                                    <h4><span class="label label-success"><i class="fa fa-exclamation-circle fa-pulse"></i> Currently rented</span></h4>
                                {% endif %}
                            </div>
					</div>			
				{% endfor %}
                {% if is_paginated %}
                <div class="pagination">
                     <ul class="pagination">
                         {% for i in page_obj.paginator.page_range %}
                            <li {%if page_obj.number == i%}class="active"{%endif%}><a href="/history/list/{{i}}">{{i}}</a></li>
                         {%endfor%}
                     </ul>
                </div>
            {% endif %}
			{% endif %}			
		</div>
	</div>
{% endblock %}


{% block extra_body %}
<script type="text/javascript">
$( document ).ready(function() {
    $(".change-rate").click( function(event){
    var x = $(event.target).text();
    $(event.target).parents(".row").first().find(".rate-input").first().val(x);
    $(event.target).parents(".row").first().find("form").submit();
    });
});
</script>
{% endblock %}

main/templates/main/rent_cancel.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    {%if rent.can_be_cancelled%}
    <form action="" method="post">{% csrf_token %}
        <p class="lead">Are you sure you want to cancel this reservation?</p>
        <div>
            <h3>{{ rent.car.producer }} {{ rent.car.model }}</h3>
            <h4>From {{ rent.start_date }} to {{ rent.end_date }}</h4>
        </div>
        <input type="submit" value="Confirm" class="btn btn-primary" />
    </form>
    {% else %}
    <p class="lead">
    Nice try!
    </p>
    <p>
    But you can't cancel this reservation.
    </p>
    {% endif %}
</div>
{% endblock %}

main/templates/main/rent_form.html
{% extends 'base.html' %}

{% block content %}

	<div class='container'>
		<h2>Rent a car</h2>
		<h3>Car parameters</h3>
		<p>
			{{ car }}
			{# Car parameters here... #}
		</p>
	
		<h3>Rent form</h3>
		<form action="" method="POST" class="form-horizontal">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="form-group">
				{{ form.start_date.errors }}
				<label for="{{ form.start_date.id_for_label }}" class="col-sm-2 control-label">Start date:</label>
                <div class='input-group date datepicker col-sm-3'>
                    {{ form.start_date }}
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </div>

			<div class="form-group">
				{{ form.end_date.errors }}
				<label for="{{ form.end_date.id_for_label }}" class="col-sm-2 control-label">End date:</label>
                <div class='input-group date datepicker col-sm-3'>
                    {{ form.end_date }}
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </div>

			<button class="btn btn-md btn-primary" type="submit">Purchase!</button>
		</form>
		<a href="{{ request.GET.ref }}" >Go back</a>
	</div>

{% endblock %}